version: '3.8'

services:
  nginx:
    image: nginx:latest
    restart: always  # Habilita o reinício automático
    # container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      # - ./nginx-conf_d:/etc/nginx/conf.d
      - ./nginx:/etc/nginx
    networks:
      - net

networks:
  net:
    driver: bridge
